"""add products

Revision ID: bd4ad18d97b0
Revises: ca8211b9c121
Create Date: 2026-02-25 14:32:50.211089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4ad18d97b0'
down_revision: Union[str, Sequence[str], None] = 'ca8211b9c121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Clients_address'), 'Clients', ['address'], unique=False)
    op.create_index(op.f('ix_Clients_first_name'), 'Clients', ['first_name'], unique=False)
    op.create_index(op.f('ix_Clients_last_name'), 'Clients', ['last_name'], unique=False)
    op.create_index(op.f('ix_Clients_phone'), 'Clients', ['phone'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_Clients_phone'), table_name='Clients')
    op.drop_index(op.f('ix_Clients_last_name'), table_name='Clients')
    op.drop_index(op.f('ix_Clients_first_name'), table_name='Clients')
    op.drop_index(op.f('ix_Clients_address'), table_name='Clients')
    op.drop_table('Clients')
    # ### end Alembic commands ###
