"""add user created_by

Revision ID: 5a03d00e509e
Revises: 51aa496bf9fa
Create Date: 2026-02-17 09:10:12.623545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a03d00e509e'
down_revision: Union[str, Sequence[str], None] = '51aa496bf9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by')
    # ### end Alembic commands ###
